AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template to create an IAM role and policy for S3 access and S3 bucket.

Parameters:
  ExternalId:
    Type: String
    Description: "External ID for Snowflake access"

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "movies-myy-093024"

  MySnowflakeIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SnowflakeAccessRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
             AWS: !Ref ExternalId
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId  # Using a parameter for flexibility
      Policies:
        - PolicyName: SnowflakeS3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:DeleteObject
                  - s3:DeleteObjectVersion
                Resource: "arn:aws:s3:::movies-myy-093024/*"  # Adjust bucket name as needed
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource: "arn:aws:s3:::movies-myy-093024"
                Condition:
                  StringLike:
                    s3:prefix: [ '*' ]

Outputs:
  SnowflakeRoleARN:
    Description: "ARN of the Snowflake IAM Role"
    Value: !GetAtt MySnowflakeIAMRole.Arn
